steps:
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vishakha-403211/password-checker', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vishakha-403211/password-checker']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'password-checker',
        '--image', 'gcr.io/vishakha-403211/password-checker',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/vishakha-403211/password-checker'
