steps:
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', ' asia-south1-docker.pkg.dev/vishakha-403211/vishnu/password-checker:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', ' asia-south1-docker.pkg.dev/vishakha-403211/vishnu/password-checker:latest']

  

images:
  -  asia-south1-docker.pkg.dev/vishakha-403211/vishnu/password-checker:latest
